# ARRAYS Vs LISTS

In [ ]:
"""
range returns a LIST
arange returns an ARRAY
"""

In [1]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum = []

for i in range(3):
    list_two[i]=list_two[i]**2
    list_three[i]=list_three[i]**3
    list_sum.append(list_two[i]+list_three[i])
print(list_sum)

[2, 12, 36]


In [ ]:
"""
With 'arange' -> arange(start,stop) this means that the generation of array starts at the starting point and ends at the ending point.
For eg,
    arange(1,10) gives output as follows
    [1,2,3,4,5,6,7,8,9]
It does not include the 'stop' variable.
"""

In [4]:
import numpy as np
 
array_two =np.arange(1,4) ** 2 #arange is for creating range of elements in array
print(array_two)

array_three = np.arange(1,4)**3
print(array_two+array_three)

[1 4 9]
[ 2 12 36]


In [6]:
# 'Power' function
np.power(np.array([1,2,3]),4) #This is a universal function

array([ 1, 16, 81], dtype=int32)

In [7]:
# 'Negative' function generates the negative of all the numbers
np.negative(np.array([2,3,4,6]))

array([-2, -3, -4, -6])

In [8]:
#Exponential function
np.exp(np.array([1,2,3,4,5]))

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [9]:
#Instead of invoking the array again and again it is better to declare it separately
sample_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [10]:
#Log function
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [11]:
# Sin function
np.sin(sample_array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

# MULTI-DIMENSIONAL ARRAY OBJECT

In [ ]:
# N dimensional array - all the elements are of the same datatype. This allows the array to compute the memory required for the array without any confusions
"""
For a 1D array, shape would be (n,)
    n-> no of elements in array
    Eg. [1 2 3 4 5] shape->(3,)
For a 2D array, shape would be (n,m)
    n->no of rows
    m->no of columns
"""

In [14]:
#Creating multi-dimensional arrays
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([x,y,z])
print(multi_array)
print(multi_array.shape)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


In [16]:
#Linspace function
"""
linspace generates values based on the specification. 
linspace(start,stop,stepsize->how much numbers to print?)
all the numbers are evenly placed.
It includes the stop variable.
"""
w = np.linspace(1,10,50)
print(w)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [18]:
#Indexing in multi-dimensional array
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(7,10)

multi_array = np.array([x,y,z])
print(multi_array)
multi_array[1,2]

[[0 1 2]
 [3 4 5]
 [7 8 9]]


5

In [ ]:
"""
The numpy 'array' object has a special feature where we can specify the datatype in the form of dtype.
""" 

# 1D slicing

In [ ]:
"""
Slicing in numpy is done using the following syntax (start,stop,stepsize)
start->specifies where we want to start slicing the array
stop->specifies where we want to stop slicing the array
stepsize-> specifies spacing inbetween the specified value
"""

In [22]:
x=np.arange(1,10)
print(x)
x[2:7:2]

[1 2 3 4 5 6 7 8 9]


array([3, 5, 7])

# Reshaping

In [25]:
x = np.arange(9)
print(x)
# We can reshape it into 2 dimensional array

x=np.arange(9).reshape(3,3)
print (x)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
y = np.arange(18).reshape(2,3,3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


6.0

# Multi-Dimensional slicing

In [35]:
"""
y = np.arange(18).reshape(3,2,3)
The output:
     0 1 2
0[[[ 0 1 2         0
     3 4 5]]       1
1  [[6 7 8         0
     9 10 11]]     1
2  [[12 13 14      0
     15 16 17]]]   1
We want to access the element '6'
y[1,0,0]
If we want to access '13'
y[2,0,1]
"""
y = np.arange(18).reshape(3,2,3)
print(y)

y[0,1,0]
y[2,0,1]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


13

In [36]:
y = np.arange(18).reshape(3,2,3)
y[1,0:2,0:3]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

# Manipulating array shapes

In [8]:
"""
ravel()- It reads a multi-dimensional array and returns a one dimensional array.
ravel returns a view of the original array.
"""
import numpy as np
x=np.arange(9).reshape(3,3)
ravelled_array=x.ravel()
print(ravelled_array)

ravelled_array[2]=19999 #If we modify the ravelled array the change is reflected in both arrays.
print(ravelled_array)
print(x)

[0 1 2 3 4 5 6 7 8]
[    0     1 19999     3     4     5     6     7     8]
[[    0     1 19999]
 [    3     4     5]
 [    6     7     8]]


In [10]:
# flat() function. Returns a copy of the original array. It allocates new memory!
flattened_array = x.flatten()
print(flattened_array)

flattened_array[2]=2000
print(flattened_array)
print(x) #Since flattened array returns a copy, the change is not reflected in the original array. Rather it is reflected only in the copy.

[    0     1 19999     3     4     5     6     7     8]
[   0    1 2000    3    4    5    6    7    8]
[[    0     1 19999]
 [    3     4     5]
 [    6     7     8]]


In [12]:
#We can use the 'shape' function directly to set the shape of the array
y=np.arange(9)
y.shape=[3,3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
#Flipping a matrix over its diagonal using the 'transpose' function.
y=np.arange(9)
y.shape=[3,3]
print(y.transpose())

# or we can use 'T'
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [18]:
# 'resize' function
print(np.resize(y,(6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [22]:
#np.zeros - > returns an array filled with zeros
print(np.zeros((6,6),dtype=int))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [24]:
# np.eye -> creates a square matrix with equal amount of rows and columns where all the diagonal elements are 1 and the other elements are zero.
#It is most often used in linear algebric functions
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
#Creating random numbers
np.random.rand(4,4)

array([[0.60394668, 0.39038908, 0.77500646, 0.22841341],
       [0.96024364, 0.41091526, 0.52049211, 0.00625862],
       [0.37608151, 0.99300949, 0.68123879, 0.46957254],
       [0.58384147, 0.16231049, 0.31715724, 0.78246414]])

# Matrix multiplication

In [29]:
import numpy as np
matrix_a = np.matrix([1,2,3,4,4,5]).reshape(2,3)
matrix_b = np.matrix([3,2,-4,5,6,7]).reshape(3,2)
product = np.matmul(matrix_a,matrix_b)
print(product)

[[13 33]
 [26 63]]


# STACKING

In [1]:
# Stacking two arrays horizontally
import numpy as np
x=np.arange(4).reshape(2,2)
print(x)

[[0 1]
 [2 3]]


In [3]:
y = np.arange(4,8).reshape(2,2)
y

array([[4, 5],
       [6, 7]])

In [6]:
#Horizontal stacking
"""
the arrays must have same shape along the second axis.
if the shape of the array is like (4,3)(4,2) it will not be acceptable in horizontal stacking. 
"""
z=np.hstack((x,y))
z
z.shape

(2, 4)

In [5]:
#Vertical stacking
"""
Joins the two arrays along the first axis. That is if the coordinates are represented as (x,y),
x-> is the first axis
y-> is the second axis
In python, as indexing starts from 0, the first axis is 0 and the second axis is 1 always.
"""
z=np.vstack((x,y))
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
#Concatenating the arrays 
"""
Concatenating the arrays along the first axis is equivalent to vstack function
Concatenating the arrays along the second axis is equivalent to hstack function
"""
w=np.concatenate((x,y),axis =0)
print(w)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [11]:
#DEPTH STACKING
depth_stack = np.dstack((x,y))
print(depth_stack)

[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]
